import { NavigatorScreenParams } from "@react-navigation/native";
import { BottomTabParamList } from "./BottomTabParamList";

export type RootStackParamList = {
    DrawerNavigation: NavigatorScreenParams<BottomTabParamList>;
    OnBoarding: undefined;
    Login: undefined;
    Register: undefined;
    ForgotPassword: undefined;
    OTPAuthentication: undefined;
    ResetPassword: undefined;
    Settings: undefined;
    ChangePassword: undefined;
    TwoStepAuthentication: undefined;
    Support: undefined;
    History: undefined;
    Verification: undefined;
    EditProfile: undefined;
    Notifications: undefined;
    Components: undefined;
    Accordion: undefined;
    BottomSheet: undefined;
    ModalBox: undefined;
    Buttons: undefined;
    Badges: undefined;
    Charts: undefined;
    Headers: undefined;
    lists: undefined;
    Pricings: undefined;
    DividerElements: undefined;
    Snackbars: undefined;
    Socials: undefined;
    Swipeable: undefined;
    Tabs: undefined;
    Tables: undefined;
    Toggles: undefined;
    Inputs: undefined;
    Footers: undefined;
    TabStyle1: undefined;
    TabStyle2: undefined;
    TabStyle3: undefined;
    TabStyle4: undefined;
};